import type { Metadata } from "next";
import "./globals.css";
import { syncUser } from "@/utils/syncUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await syncUser(); // Ensures the user is stored in Supabase

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
